name: Scala CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build project
      run: sbt compile
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: sbt coverage generate
      run: sbt coverage test
    - name: sbt coverageReport
      run: sbt coverageReport
    - name: pwd
      run: pwd
    - name: ls target scala
      run: du -a target/scala-2.13/
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        fail_ci_if_error: true
        verbose: true
        directory: /home/runner/work/PrivateHome/PrivateHome/target/scala-2.13/scoverage-data/
